import { mainColors } from "@/utils/global-theme";
import { StyleSheet } from "react-native";

export const buttonS = StyleSheet.create({
  primary: {
    flexDirection: "row",
    gap: 2,
    backgroundColor: mainColors.primary,
    paddingVertical: mainColors.sm,
    paddingHorizontal: mainColors.md,
    borderRadius: mainColors.radius,
    alignItems: "center",
    justifyContent: "center",
  },
  secondary: {
    flexDirection: "row",
    gap: 2,
    backgroundColor: mainColors.accent,
    paddingVertical: mainColors.sm,
    paddingHorizontal: mainColors.md,
    borderRadius: mainColors.radius,
    alignItems: "center",
    justifyContent: "center",
  },
  outline: {
    flexDirection: "row",
    gap: 2,
    backgroundColor: mainColors.secondary,
    paddingVertical: mainColors.sm,
    paddingHorizontal: mainColors.md,
    borderWidth: 1,
    color: mainColors.accentForeground,
    borderColor: mainColors.accent,
    borderRadius: mainColors.radius,
    alignItems: "center",
    justifyContent: "center",
  },
  ghost: {
    flexDirection: "row",
    gap: 2,
    backgroundColor: "transparent",
    paddingVertical: mainColors.sm,
    paddingHorizontal: mainColors.md,
    borderRadius: mainColors.radius,
    alignItems: "center",
    justifyContent: "center",
  },
  destructive: {
    flexDirection: "row",
    gap: 2,
    backgroundColor: mainColors.destructive,
    paddingVertical: mainColors.sm,
    paddingHorizontal: mainColors.md,
    borderRadius: mainColors.radius,
    alignItems: "center",
    justifyContent: "center",
  },
})
